### ISSUE TITLE
Persist code in local storage

### ISSUE THREAD

**Issue by waynevanson** [hrgdavor/jscadui#104]
The code I write in the sidebar is replaced by the default text when I press save.

Is that supposed to happen? If not I'll look into it.

**Comment by hrgdavor** [comment]
Hi, just tried it on https://jscad.app

pressing ctrl+S or the save link on the bottom, opens a save dialog in Chrome, and only re-renders the model in FireFox ... unfortunalety firefox refuses to implement any of the file related features that would allow this kind of IDE in browser to save files ... they just play for the Cloud crowd sadly.
