### ISSUE TITLE
slider behavior bumpy when crossing from <100 to ≥100 and vice versa

### ISSUE THREAD

**Issue by Hermann-SW** [hrgdavor/jscadui#111]
The problem is that the slider value box changes its size and moves the slider on its right to new postion. Since the mouse cursor remains at same position on display, slider values jump around in a bumpy way. Somehow the slider position needs to be fixed to avoid the bumpy behavior:
![recording mp4](https://github.com/user-attachments/assets/9819c7b9-4c2f-4e41-a849-8f8eda5d914f)

**Comment by Hermann-SW** [comment]
I verified on @othelarian branch, works !
![Peek_2024-07-12_23-13](https://github.com/user-attachments/assets/96b04c05-3787-447a-bfd7-4ec4fc1183ea)

**Comment by hrgdavor** [comment]
This fix should be live no. Try and close issue if OK.

**Comment by Hermann-SW** [comment]
Tested to work fine with this link, redirecting to jscad.app:
https://hermann-sw.github.io/lattice_sphere_cmp/pt.html
