### ISSUE TITLE
[animation] scene render time always 0 during animation

### ISSUE THREAD

**Issue by Hermann-SW** [hrgdavor/jscadui#117]
render time bottom right should be updated for each frame of the animation

**Comment by hrgdavor** [comment]
not sure if you caught the issue that got fiexed in the meantime, or you used examples that cache mesh.
cached mesh is very fast and could easily give you zero render time.

here is example with random segment count and slow anim.

https://3d.hrg.hr/jscad/anim/#data:application/gzip;base64,H4sIABlxsmYAA4VSwW7bMAy9+yuIXmxnWuJm6w4GAmzHHAb0sFvRg2AzjQZZ1CiqTWH430fbWXbsSST1nh75qI5CEvidOtvDARj/ZMdYld+Xym6gHr0LL2VdrMARvXcxkesnhS+gbWQ3OHGvmP6BmMQKGhC2IXkN/4OX0ol4SMUV3dnujLP4DV09NaYx982zualVI9ve5dQ+3c83Zt88T/WtqcfjLPDTyrnY7UDeCASTbMCFmCWBZYScVEMIEiKc6Q28facsoJ1A8q5HhpNTKMlZwyuvOOXQiaMAg3WhGvXt1ZfP0bLVCWDR+YUXOc6MQ2lLMxcPjVHsj+AGu9BHeY/Y3q1CdwYGF9pGD3tp9waSYGybbbPX0imm9kFPr3a2wllNtFkoiWW55p4otiXjK3LCclI9JR0eTDHVoyYeRYd8GTDoBKspW6Yc+urL/tOa2dDTUNWbb19rJTBK5gDrzmbrH48bMR+Yr11fNeY1TEWhPyV73OIlEi/C4+zZ9BeGIm/hXwIAAA==
