### ISSUE TITLE
Allow hierarchy export in 3MF

### ISSUE THREAD

**Issue by elalish** [hrgdavor/jscadui#32]
Regarding https://github.com/elalish/manifold/pull/500#discussion_r1269787145

Currently, if you use the `meshes` and `components` inputs of [`to3dmodel`](https://github.com/hrgdavor/jscadui/blob/main/file-format/3mf-export/index.js), you can't create a real scene hierarchy. This is because every component becomes an item, so any component that's referenced by another gets copied as it becomes a new tree root. 

I propose adding another input, `items`, which will refer to the IDs of the components that are actually meant to be roots. `simple` can remain unchanged, as that is a nice shortcut. I'm happy to make a PR for this, if someone would be so kind as to push a release to npm with it.

**Comment by hrgdavor** [comment]
cool. I will push the version right away after approving.

**Comment by hrgdavor** [comment]
fixed
