### ISSUE TITLE
Add camera-view controller

### ISSUE THREAD

**Issue by kevinmamaqi** [hrgdavor/jscadui#4]
Create a camera-view controller as in other popular 3D CAD libraries. Example on threejs: https://github.com/isRyven/ViewCubeControls

Move it to regl

**Comment by hrgdavor** [comment]
more likely we use Threejs as engine and moving to regl maybe sometime in the future. I know only a little about regly, I was hacking it few times to improve the shader code.

**Comment by hrgdavor** [comment]
the code there is unfinished, WIP.

there is also this one
https://github.com/yoavmil/angular-threejs-starter/tree/nav-cube/src/app/nav-cube

looks like it is something we will have to finish implementing

**Comment by hrgdavor** [comment]
This was implemented in https://github.com/hrgdavor/jscadui/tree/main/packages/html-gizmo
