### ISSUE TITLE
allow module that exports only the function

### ISSUE THREAD

**Issue by hrgdavor** [hrgdavor/jscadui#77]
as discussed here https://github.com/jscad/OpenJSCAD.org/issues/1318#issuecomment-1896245210

this script does not work and it should to match openjscad.xyz

```js
module.exports=function main(){return require('@jscad/modeling').primitives.sphere({radius: 50})}
```

**Comment by hrgdavor** [comment]
@Hermann-SW this is now fixed and on temporary url until merged into main and pushed to jscad.app

https://3d.hrg.hr/jscad/app1/#data:application/javascript;base64,bW9kdWxlLmV4cG9ydHM9ZnVuY3Rpb24gbWFpbigpe3JldHVybiByZXF1aXJlKCdAanNjYWQvbW9kZWxpbmcnKS5wcmltaXRpdmVzLnNwaGVyZSh7cmFkaXVzOiA1MH0pfQ==

**Comment by Hermann-SW** [comment]
I tested under Debian based 64bit Raspberry Pi OS.
Works for firefox !
Does not work (empty display) for chromium-browser :-(

**Comment by hrgdavor** [comment]
@Hermann-SW that is strange, it works on my PC, chrome and vivaldi browser. could it be cahce ? try CTRL+F5 ?

**Comment by Hermann-SW** [comment]
@hrgdavor The browser is not chrome, that does not exist for ARM.
I pressed CTRL+F5 and recorded with peek screenrecorder.
After quite some activity, no display:
![https://stamm-wilbrandt.de/videos/Peek_2024-01-17_22-04.gif](https://stamm-wilbrandt.de/videos/Peek_2024-01-17_22-04.gif)

**Comment by Hermann-SW** [comment]
@hrgdavor other scripts work in chromium browser.
And the small script in editor without data uri does not work either in chromium.
Perhaps one of your developers has access to a Raspberry Pi SBC and can test with chromium.

**Comment by hrgdavor** [comment]
> Perhaps one of your developers has access to a Raspberry Pi SBC and can test with chromium.

Sadly, I doubt. me a @platypii are active here, and we both contribute to jscad along with one more developer taht is main dev of jscad.

If you want, come to our discord, and we could see if we can get to bottom of this. Maybe even some remote desktop access.
